### ISSUE TITLE
Get key requires a fallback value

### ISSUE THREAD

**Issue by fadils** [tumblr/Remember#11]
The README shows

``` JAVA
String value = Remember.getString("some key");
```

While the actual code is:

``` JAVA
public static String getString(String key, String fallback)
```

Shouldn't we make the `fallback` optional so that the operation in README can actually be done?
Something like

``` JAVA
public static String getString(String key) {
    getString(key, null);
}
```

**Comment by mlapadula** [comment]
My mistake, I had the wrong syntax in the README. The README is now updated to match the actual code.

For the main point though: IMO defaults should always be explicit. Otherwise you end up null-checking everywhere, or second-guessing yourself whenever you want to grab a value.
