### ISSUE TITLE
Get the value only from memory and not from disk....

### ISSUE THREAD

**Issue by bakeny** [tumblr/Remember#14]
```
/**
 * Gets the value mapped by the given key, casted to the given class. If the value doesn't exist or isn't of the
 * right class, return null instead.
 */
private <T> T get(String key, Class<T> clazz) {
    Object value = mData.get(key);
    T castedObject = null;
    if (clazz.isInstance(value)) {
        castedObject = clazz.cast(value);
    }
    return castedObject;
}
```

**Comment by KevinTCoughlin** [comment]
Can you clarify the issue here? You only pasted an existing method.

**Comment by bakeny** [comment]
i  means:
   when we save values likes this:
   // Put it in memory
   mData.put(key, value);

   // Save it to disk
  ........

but when we get the saved values only from memory rather than from disk  likes this:
private <T> T get(String key, Class<T> clazz) {
    Object value = mData.get(key);
    T castedObject = null;
    if (clazz.isInstance(value)) {
        castedObject = clazz.cast(value);
    }
    return castedObject;
}

**Comment by KevinTCoughlin** [comment]
Sorry, I still don't fully understand. Do you want to only put a value in memory and never save it to disk?

**Comment by bakeny** [comment]
I mean the logic of keeping the value is to store in memory and then saved to the hard drive, in the source code why there is only  logical of geting value from memory  and do not get the logic value from a hard disk inside

------------------------------------------------------------------发件人：Kevin Coughlin notifications@github.com发送时间：2015年5月29日(星期五) 20:04收件人：tumblr/Remember Remember@noreply.github.com抄　送：Rain yan.rui@aliyun.com主　题：Re: [Remember] Get the value only from memory and not from disk.... (#14)
Sorry, I still don't fully understand. Do you want to only put a value in memory and never save it to disk?

**Comment by KevinTCoughlin** [comment]
Remember's intent is to stay in-sync with disk via `SharedPreferences`. On init it loads all of `SharedPreferences` into memory. This will hold true for all cases except for if OOM forces the application to unexpectedly quit and the write to not succeed.

As stated in the README:

> Note that since writes are asynchronous, an in-flight write may be lost if the app is killed before the data has been written to disk. If you require true 'commit' semantics then Remember is not for you.

Initialization:
https://github.com/tumblr/Remember/blob/master/remember/src/main/java/com/tumblr/remember/Remember.java#L82
