### ISSUE TITLE
 synchronous saving

### ISSUE THREAD

**Issue by kamilwlf** [tumblr/Remember#15]
now we have:
`public static Remember putFloat(String key, float value) {
        return getInstance().saveAsync(key, Float.valueOf(value), (Remember.Callback)null);
    }`

it will be nice to have standard approach:
`public static Remember putFloatSync(String key, float value) {
        return getInstance().saveSync(key, Float.valueOf(value));
    }`

**Comment by KevinTCoughlin** [comment]
As mentioned in the README, all writes are asynchronous when using Remember.

```
Note that since writes are asynchronous, an in-flight write may be lost if the app is killed before the data has been written to disk. If you require true 'commit' semantics then Remember is not for you.
```

I'm going to close this issue as async writes are core to our current implementation.
