### ISSUE TITLE
initialize contex only once

### ISSUE THREAD

**Issue by kamilwlf** [tumblr/Remember#16]
`When your app starts up, initialize Remember. This only has to be done once, and should happen in your app's onCreate():`
This is great. Can you explain how it works? and where can I read about it ? or how to do it in own class?

Context management has always been my bigest problem

**Comment by mlapadula** [comment]
Sure, check out and build the sample app, and look at SampleApp.java ([this file](https://github.com/tumblr/Remember/blob/master/sample-app/src/main/java/com/tumblr/remembersample/SampleApp.java)). It extends Application, and its onCreate() happens before anything else in your app. 

Android docs: http://developer.android.com/reference/android/app/Application.html#onCreate()
