### ISSUE TITLE
Are the values ​​recorded by the library I can use it in the normal way? compatibility

### ISSUE THREAD

**Issue by kamilwlf** [tumblr/Remember#2]
question concerns the compatibility

Are the values ​​recorded by the library I can use it in the normal way ?

like this:
getSharedPreferences(String, int)
?
http://developer.android.com/reference/android/content/SharedPreferences.html

**Comment by mrfanr** [comment]
@kamilwlf Obviously you can! The library writes to SharedPreferences file
