### ISSUE TITLE
Publish artifacts to Maven Central?

### ISSUE THREAD

**Issue by fadils** [tumblr/Remember#5]
Any chance for this?

**Comment by jitpack-io** [comment]
Hi!
Not sure what the release plan is but right now it's possible to install Remember as a gradle/maven dependency from: https://jitpack.io/#tumblr/Remember/2b7ead0d47

Would be a bit nicer if there was a GitHub release.

**Comment by fadils** [comment]
Hey @jitpack-io!
Awesome, it works..
I guess I'll leave this issue open as a reference. At least, for now.

**Comment by KevinTCoughlin** [comment]
Done - #6
