### ISSUE TITLE
GitHub release

### ISSUE THREAD

**Issue by jitpack-io** [tumblr/Remember#6]
Hi!

Would be nice to have a GitHub release of Remember

**Comment by mlapadula** [comment]
Done!

**Comment by jitpack-io** [comment]
Cool! Works like a charm:
https://jitpack.io/#tumblr/Remember/v1.0

Perhaps it's an idea to add this dependency info in the readme. Happy to submit a PR if you're interested.

**Comment by KevinTCoughlin** [comment]
https://github.com/tumblr/Remember/commit/af754a3b34c120b074e818d35dfe319d84e3d3eb - added to README
