### ISSUE TITLE
remind something

### ISSUE THREAD

**Issue by hongyangAndroid** [tumblr/Remember#7]
I see your code 

``` java
private <T> Remember saveAsync(final String key, final T value, final Function<Boolean,Void> callback) {
        // Put it in memory
        mData.put(key, value);

        // Save it to disk
        new AsyncTask<Void,Void,Boolean>() {
            @Override
            protected Boolean doInBackground(Void... params) {
                return saveToDisk(key, value);
            }

```

you put it in memory first ,then write it to disk async .
but  

``` java
private boolean saveToDisk(final String key, final Object value) {
                 //...
            if (didPut) {
                success = editor.commit();
            }
        }
```

we can see after you put data to memory , the data might be can not add to disk . 
So , Whether need if(!suceess){mData.remove()} ? or you can check its' type first .

**Comment by KevinTCoughlin** [comment]
The methods that expose a callback return `true` or `false` indicating whether or not the value was successfully saved to disk.

**Comment by hongyangAndroid** [comment]
but you have saved  in memory even if callback return false .

**Comment by KevinTCoughlin** [comment]
Similar to #14. The intent is to load `SharedPreferences` into memory and keep them in-sync. You could implement the Callback pattern and manipulate memory as you wish for the failure case.
