### ISSUE TITLE
Add JavaDoc

### ISSUE THREAD

**Issue by KevinTCoughlin** [tumblr/Remember#8]
It would be helpful for devs to include JavaDoc which we can host on Github. See [jumblr](https://github.com/tumblr/jumblr) as an example.

**Comment by mlapadula** [comment]
Done -- https://cdn.rawgit.com/tumblr/Remember/master/doc/com/tumblr/remember/Remember.html

(Hosted on rawgit.com until I can figure out the gh-pages setup for this repo)
