### ISSUE TITLE
Serialize primitive arrays?

### ISSUE THREAD

**Issue by Brian-McBride** [tumblr/Remember#9]
To kick it up a notch over simply managing your own SharedPreferences instance.

Serializing and Deserializing arrays would be nice.

**Comment by mlapadula** [comment]
Remember is meant to be a wrapper around SharedPreferences. Serializing/deserializing arrays is kind of out of scope, and even picking a serialization scheme is something that can get very application-specific. Going to close this, but thanks for the feedback :)
